services:
  panel_admin:
    build: .
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
